# Generated by Django 2.2.6 on 2019-10-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_on_completion',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certification', to='course_selector.Certification'),
        ),
    ]
