# Generated by Django 2.2.6 on 2019-10-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0002_course_comp_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='course_selector.Course'),
        ),
    ]
