# Generated by Django 2.2.6 on 2019-10-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0002_auto_20191011_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_earned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course_selector.Certification'),
        ),
    ]
