# Generated by Django 2.2.6 on 2019-10-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0003_auto_20191011_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='courses',
            field=models.ManyToManyField(related_name='courses_included', to='course_selector.Course'),
        ),
    ]
