# Generated by Django 2.2.6 on 2019-10-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0003_course_prereqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prereqs',
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(related_name='_course_prereqs_+', to='course_selector.Course'),
        ),
    ]
