# Generated by Django 2.2.6 on 2019-10-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0004_auto_20191012_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.URLField(default='http://www.wgu.edu'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='courses',
            field=models.ManyToManyField(related_name='degrees', to='course_selector.Course'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
