# Generated by Django 2.2.6 on 2019-10-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0004_auto_20191010_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_prereqs_+', to='course_selector.Course'),
        ),
    ]
