# Generated by Django 2.2.6 on 2019-10-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0006_auto_20191026_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degrees', to='course_selector.School'),
        ),
    ]
