# Generated by Django 2.2.6 on 2019-10-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_selector', '0007_auto_20191026_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course_selector.CourseType'),
        ),
    ]
